### ISSUE TITLE
jamplus3 workspace - missing compiler settings

### ISSUE THREAD

**Issue by jbrandwood** [jamplus/jamplus#32]
Problem:

On jamplus3 workspace builds, the compiler auto-detect setup stage is skipped leaving any compiler defines and paths unset, which means that they can't be passed on to the workspace.

This kills Visual Studio intellisense because the SDK header paths and any compiler-specific #defines are not initialized.

Note - this doesn't actually fix the intellisense, that requires other changes as well. But without this the other changes aren't even possible.

Solution:

In /modules/toolchains/c/_default_.jam, line 3, change ...

-if ! $(TARGETINFO_LOCATE) {
+if $(C.PLATFORM) != *  &&  $(C.CONFIG) != * {

**Comment by jamplus** [comment]
I think this has long since been fixed, so I am closing the issue. Reopen if it is still a problem.
