### ISSUE TITLE
jamplus3 workspace -  missing intellisense defines and includes

### ISSUE THREAD

**Issue by jbrandwood** [jamplus/jamplus#33]
Problem:

The global "C.Defines *" settings are not exported in the Visual Studio workspace's "NMake Preprocessor Definitions".
The MSSDK_STDHDRS are not exported in the Visual Studio workspace's "NMake Include Search Path".

This severely spoils intellisense for the project.

Solution:

To fix the missing defines, in scripts/DumpJamTargetInfo.jam, line 128, change

#on $(C.ACTIVE_TOOLCHAIN_*) {
#defines += $(DEFINES) ;
#hdrs += $(HDRS) ;
#}

to

on $(C.ACTIVE_TOOLCHAIN_*) {
defines += $(DEFINES) ;
hdrs += $(HDRS) ;
}

To fix the missing includes, in scripts/DumpJamTargetInfo.jam, line 144, change

hdrs += $(SUBDIRHDRS) $(STDHDRS) ;

to

hdrs += $(SUBDIRHDRS) $(STDHDRS) $(C.STDHDRS:Z=$(C.COMPILER_SUITE_SYMBOL)) ;

**Comment by jamplus** [comment]
I think this has long since been fixed, so I am closing the issue.
