### ISSUE TITLE
Bootstrapping fails on Arch Linux

### ISSUE THREAD

**Issue by pkl97** [jamplus/jamplus#38]
Bootstrapping on Arch Linux x86_64 fails with these errors:

./bootstrap-linux64.sh

make all CFLAGS=" -fexceptions -m64" LINKLIBS=" -m64" PLATFORM=linux64
make[1]: Entering directory '/home/peter/devel/jamp/jamplus/src'
./jam0 -sJAM_MODULES_PATH=../bin/modules -f../bin/Jambase.jam -sCONFIG=releaseltcg -sPLATFORM=linux64
don't know how to make luaplus/.build/bin.lua52-luaplus.gcc.linux64/share/lua/5.2/copas.lua
don't know how to make luaplus/.build/bin.lua52-luaplus.gcc.linux64/share/lua/5.2/coxpcall.lua
don't know how to make luaplus/.build/bin.lua52-luaplus.gcc.linux64/share/lua/5.2/expand.lua
don't know how to make luaplus/.build/bin.lua52-luaplus.gcc.linux64/share/lua/5.2/getopt.lua
don't know how to make luaplus/.build/bin.lua52-luaplus.gcc.linux64/share/lua/5.2/lanes.lua
...
**\* found 293 target(s)...
**\* updating 8 target(s)...
**\* can't find 38 target(s)...
**\* can't make 38 target(s)...
**\* skipped ../bin/linux64/lua/share/lua/5.2/copas.lua for lack of luaplus/.build/bin.lua52-luaplus.gcc.linux64/share/lua/5.2/copas.lua...
**\* skipped ../bin/linux64/lua/share/lua/5.2/coxpcall.lua for lack of luaplus/.build/bin.lua52-luaplus.gcc.linux64/share/lua/5.2/coxpcall.lua...
**\* skipped ../bin/linux64/lua/share/lua/5.2/expand.lua for lack of luaplus/.build/bin.lua52-luaplus.gcc.linux64/share/lua/5.2/expand.lua...
**\* skipped ../bin/linux64/lua/share/lua/5.2/getopt.lua for lack of luaplus/.build/bin.lua52-luaplus.gcc.linux64/share/lua/5.2/getopt.lua...
**\* skipped ../bin/linux64/lua/share/lua/5.2/lanes.lua for lack of luaplus/.build/bin.lua52-luaplus.gcc.linux64/share/lua/5.2/lanes.lua...
...
**\* skipped 38 target(s)...
**\* updated 8 target(s)...
**\* finished in 0.09 sec
Makefile.Common:116: recipe for target 'all' failed
make[1]: **\* [all] Error 1
make[1]: Leaving directory '/home/peter/devel/jamp/jamplus/src'
Makefile:53: recipe for target 'linux64' failed
make: **\* [linux64] Error 2

These steps fix the problem:
- cd src/luaplus/.build
- ln -s linux64/bin/ bin.lua52-luaplus.gcc.linux64
- cd -
- ./bootstrap-linux64.sh

It seems Lua binaries are not built in the directory where they are later expected to be.

**Comment by pkl97** [comment]
Today's version of jamplus builds fine on Arch Linux.

**Comment by jjensen** [comment]
Sweet!
