### ISSUE TITLE
fileglob of path with "+" triggers 'filesAndFolders'?

### ISSUE THREAD

**Issue by erique** [jamplus/jamplus#40]
This code
```
		///////////////////////////////////////////////////////////////////////
		// Check for +
		else if (ch == '+') {
			self->filesAndFolders = 1;
			if (srcPtr - 1 == lastSlashPtr)
				++lastSlashPtr;
		}
```
[https://github.com/jamplus/jamplus/blob/master/src/fileglob.c#L951](url)
somehow makes globing a path with "+" in it (say llvm-c++) not working when used in $(var:W=..)
Yet I can't find any mention of this behavior in the docs..

**Comment by erique** [comment]
Basically - what is the point of checking for '+', and how does one populate a list based on a directory path that includes '+'?
Can the check be removed to allow paths with '+', and if not, should the docs be updated to match the behavior and how to deal with paths with '+'?

**Comment by jamplus** [comment]
The documentation was out of date until 6ffc6a2ea5cb6a736db875c12c1196b053f8e7bd.

Anyway, the + symbol has now been replaced with @* in the pattern. Hopefully, that works better for you.

I'd still like to have a syntax where files and folders can be activated for simple wildcards, but I can't come up with one. Any ideas?
